const palettes = {
  dark: {
    black: "#000000",
    red: "#ed4e4c",
    green: "#01c800",
    yellow: "#d2c057",
    blue: "#2774f0",
    magenta: "#a142f4",
    cyan: "#12b5cb",
    white: "#cfd0d0",
    gray: "#898989",
    redBright: "#f28b82",
    greenBright: "#01c801",
    yellowBright: "#ddfb55",
    blueBright: "#669df6",
    magentaBright: "#d670d6",
    cyanBright: "#84f0ff",
    whiteBright: "#FFFFFF",
  },
  light: {
    black: "#000000",
    red: "#AA0000",
    green: "#00AA00",
    yellow: "#AA5500",
    blue: "#0000AA",
    magenta: "#AA00AA",
    cyan: "#00AAAA",
    white: "#AAAAAA",
    gray: "#555555",
    redBright: "#FF5555",
    greenBright: "#55FF55",
    yellowBright: "#FFFF55",
    blueBright: "#5555FF",
    magentaBright: "#FF55FF",
    cyanBright: "#55FFFF",
    whiteBright: "#FFFFFF",
  },
};

const toCss = (property, color) =>
  `${property}: light-dark(${palettes.light[color]}, ${palettes.dark[color]})`;

const styles = {
  reset: [0, 0],
  bold: [1, 22, "font-weight: bold"],
  dim: [2, 22, "font-weight: lighter"],
  italic: [3, 23, "font-style: italic"],
  underline: [4, 24, "text-decoration: underline"],
  blink: [5, 25],
  inverse: [7, 27],
  hidden: [8, 28, "color: transparent"],
  strikethrough: [9, 29, "text-decoration: line-through"],
  doubleunderline: [21, 24, "text-decoration: underline double"],
  black: [30, 39, toCss("color", "black")],
  red: [31, 39, toCss("color", "red")],
  green: [32, 39, toCss("color", "green")],
  yellow: [33, 39, toCss("color", "yellow")],
  blue: [34, 39, toCss("color", "blue")],
  magenta: [35, 39, toCss("color", "magenta")],
  cyan: [36, 39, toCss("color", "cyan")],
  white: [37, 39, toCss("color", "white")],
  bgBlack: [40, 49, toCss("background", "black")],
  bgRed: [41, 49, toCss("background", "red")],
  bgGreen: [42, 49, toCss("background", "green")],
  bgYellow: [43, 49, toCss("background", "yellow")],
  bgBlue: [44, 49, toCss("background", "blue")],
  bgMagenta: [45, 49, toCss("background", "magenta")],
  bgCyan: [46, 49, toCss("background", "cyan")],
  bgWhite: [47, 49, toCss("background", "white")],
  framed: [51, 54, "border: 1px solid"],
  overlined: [53, 55, "text-decoration: overline"],
  gray: [90, 39, toCss("color", "gray")],
  redBright: [91, 39, toCss("color", "redBright")],
  greenBright: [92, 39, toCss("color", "greenBright")],
  yellowBright: [93, 39, toCss("color", "yellowBright")],
  blueBright: [94, 39, toCss("color", "blueBright")],
  magentaBright: [95, 39, toCss("color", "magentaBright")],
  cyanBright: [96, 39, toCss("color", "cyanBright")],
  whiteBright: [97, 39, toCss("color", "whiteBright")],
  bgGray: [100, 49, toCss("background", "gray")],
  bgRedBright: [101, 49, toCss("background", "redBright")],
  bgGreenBright: [102, 49, toCss("background", "greenBright")],
  bgYellowBright: [103, 49, toCss("background", "yellowBright")],
  bgBlueBright: [104, 49, toCss("background", "blueBright")],
  bgMagentaBright: [105, 49, toCss("background", "magentaBright")],
  bgCyanBright: [106, 49, toCss("background", "cyanBright")],
  bgWhiteBright: [107, 49, toCss("background", "whiteBright")],
};

export { palettes, styles };
